version: '2.3'
services:

  jenkins:
    container_name: jenkins
    restart: always
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
      - '50000:50000'
      - '50022:50022'
    environment:
      - TZ=Asia/Shanghai
        JAVA_OPTS="-Xmx1024m"
        JENKINS_OPTS=" --handlerCountMax=300"
    volumes:
      - /data/site_data/jenkins_home:/var/jenkins_home

  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    container_name: wp
    ports:
      - ${IP}:1080:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - /data/site_data/wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.17-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /data/logs/nginx:/var/log/nginx
      - /data/site_data/nginx-web:/var/www
    depends_on:
      - wp
      - jenkins

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    container_name: mysql-db
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - /data/site_data/db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
    db_data: {}
